[[language]]
name = "html"
formatter = { command = 'node_modules/.bin/prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'node_modules/.bin/prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'node_modules/.bin/prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'node_modules/.bin/prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'node_modules/.bin/prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'node_modules/.bin/prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = 'node_modules/.bin/prettier', args = ["--parser", "yaml"] }
auto-format = true
